=== ASJoker76/vacationspotinindonesia/xml/contacts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:con ="http://www.around-the-world.com/Contacts"
    targetNamespace="http://www.around-the-world.com/Contacts"
    elementFormDefault="qualified">
    
    <xsd:element name="Contact" type="con:dt_contact"/>
    <xsd:complexType name="dt_contact">
        <xsd:sequence>
            <xsd:element  name="autors"  type="con:aut" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    
    
    <xsd:complexType name="aut">
        <xsd:sequence>
            <xsd:element name="Name"     type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Phone-no" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Email"    type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Photo"    type="xsd:string" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ASJoker76/vacationspotinindonesia/xml/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="contacts.xsl"?>
<Contact xmlns="http://www.around-the-world.com/Contacts"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.around-the-world.com/Contacts file:/F:/Kuliah/Q3/Project%20HTML/Around%20The%20World/xml/contacts.xsd">
    <autors>
        <Name>Agus Setiawan</Name>
        <Phone-no>08971729681</Phone-no>
        <Email>agussmata76@gmail.com</Email>
        <Photo>images/agus.jpg</Photo>
    </autors>
    <autors>
        <Name>Muhammad Abdul Ghofar</Name>
        <Phone-no>085770594768</Phone-no>
        <Email>Abdulghofarmuhammad@gmail.com</Email>
        <Photo>images/ghofar.jpg</Photo>
    </autors>
</Contact>
