=== ASJoker76/vacationspotinindonesia/xml/feedback.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   
    elementFormDefault="qualified">
    <xsd:element name="Feedbackdata" type="dt_feedbck"/>
    <xsd:complexType name="dt_feedbck">
        <xsd:sequence>
            <xsd:element  name="Feedback" type="back" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType> 
    <xsd:complexType name="back">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="email" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="comment" type="xsd:string" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="ID_Feedback" type="id_feedback" use="required"/>
    </xsd:complexType>
    
    <xsd:simpleType id="ID" name="id_feedback">
        <xsd:restriction base="xsd:string">
            <xsd:length value="4"/>
        </xsd:restriction>
    </xsd:simpleType>
    
</xsd:schema>

=== ASJoker76/vacationspotinindonesia/xml/feedback.xml
<?xml version="1.0"?>
<Feedbackdata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/F:/Vocation-spot-in-indonesia/xml/feedback.xsd">
	<Feedback ID_Feedback="F001">
		<name>Agus</name>
		<email>agus@gmail.com</email>
		<comment>I like it</comment>
	</Feedback>
	<Feedback ID_Feedback="F003"><name>bagus</name><email>bgs@gmail.com</email><comment>bagus</comment></Feedback><Feedback ID_Feedback="F004"><name>nila</name><email>nil@gmail.com</email><comment>wonderfull</comment></Feedback><Feedback ID_Feedback="F005"><name>zulfi</name><email>zul@gmail.com</email><comment>great</comment></Feedback><Feedback ID_Feedback="F006"><name>satria</name><email>sat@gmail.com</email><comment>bagus</comment></Feedback><Feedback ID_Feedback="F007"><name>tika</name><email>tikjaw@gmail.com</email><comment>keren</comment></Feedback></Feedbackdata>
