=== ASJoker76/vacationspotinindonesia/xml/Pulau.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:pu ="http://www.around-the-world.com/"
    targetNamespace="http://www.around-the-world.com/"
    elementFormDefault="qualified">
    <xsd:include schemaLocation="validasi.xsd"/>
    <xsd:element name="all-pulau" type="pu:dt_pulau"/>
    <xsd:complexType name="dt_pulau">
        <xsd:sequence>
            <xsd:element  name="DetailPulau"  type="pu:ppulau" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    
    
    <xsd:complexType name="ppulau">
        <xsd:sequence>
            <xsd:element name="Nama_pulau" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Name_tempat" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Small-Description" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Description" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Last-Description" type="xsd:string" maxOccurs="1"/>
            <xsd:element name="Image"       type="xsd:string" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="ID_PPulau" type="pu:PulauID" use="required"/>
    </xsd:complexType>
</xsd:schema>

=== ASJoker76/vacationspotinindonesia/xml/Pulau.xml
<?xml version="1.0" encoding="UTF-8"?>
<all-pulau xmlns="http://www.around-the-world.com/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.around-the-world.com/ file:/F:/Vocation-spot-in-indonesia/xml/Pulau.xsd">
    <DetailPulau ID_PPulau="P001">
        <Nama_pulau>Jawa</Nama_pulau>
        <Name_tempat>Mount Bromo</Name_tempat>
        <Small-Description>Mount Bromo is one of the active volcanoes in Indonesia, 
            precisely in East Java and covers four districts namely Probolinggo, Pasuruan, Lumajang and Malang. 
            As the volcano is still active, 
            so Bromo-known tourist destination in East Java and almost never empty every day.</Small-Description>
        <Description>Status = still active
            H = 2,392 meters above sea level
            has its vast sea of ​​sand = (- / +) 5,300 hectares
            
            Mount Bromo in Probolinggo travel icon known as the most beautiful and most visited. The word "Bromo" comes from the word "Brahma" is one of the Gods of Hinduism. 
            Mount Bromo is not as large as other volcanoes in Indonesia but the scenery is fabulous Bromo all. 
            The beauty of Mount Bromo outstanding makes tourists amazed.
            
            Communities around Mount Bromo will celebrate the festival Yadnya Kasada or Kasodo annually by describing the offerings such as vegetables, 
            chicken, and the money will be offered to the gods and thrown into the crater of Mount Bromo. 
            As a form of gratitude to the almighty.
            
            Activities Mount Bromo
            
            The eruption in 2004 Mount Bromo erupted in 2004. The eruption resulted in the death of two people because the exposed rocks of volcanic eruptions. 
            The eruption in 2010 On Tuesday, November 23rd, 2010, at 16.30 WIB (Western Indonesia Time), 
            Center for Volcanology and Indonesia Geological Hazard Mitigation (CVGHM) confirmed that 
            the status of activity at Mount Bromo was "alert" because of the increasing activity of 
            tremors and volcanic earthquakes shallow happened on the mountain. 
            The eruption in 2011 The eruption of Mount Bromo on January 22, 2011 05:30 
            made crater of Mount Bromo to not visible) Tengger still active at the end of January 2011, 
            the activities were marked by fluctuations of the ongoing eruption.
        </Description>
        <Last-Description>History Mount Bromo
            
            Antiquity when the kingdom of Majapahit received many attacks from all regions, 
            many natives so confused to find a new place to live until they finally split into 2 parts. 
            One heading to Bali, two to Mount Bromo. Second place is until now have in common is equally embraced Hinduism.
            The name "Tengger" is believed to come from the legend Anteng Roro and Joko Seger. 
            "Teng" is Roro An-name suffix "teng" and "ger" is the suffix of the name of Joko As "ger" and Mount Bromo also believed to be a sacred mountain. 
            Hindu communities call it by the name of Mount Brahma. While the Javanese call it Mount Bromo. Less like that of origin - origin of the legend of Mount Bromo.
            
            The crater of Mount Bromo
            To be able to reach the location of the crater of Mount Bromo travel, 
            from where parki Jeep visitors can use the services of rent a horse or walk approximately 1.5 km to reach the stairs which numbers about 250. 
            The road is impassable sandy and passed the Holy Temple Tribe Tengger commonly functioned to implement Yadya Kasada celebrations or commonly called by the name of Kasodo ceremony, 
            according to legend came from the crater Bromo Tengger volcanic eruptions. With a diameter of approximately 800 meters (north-south) and approximately 600 meters (east-west). 
            While the hazardous area of ​​a circle with a radius of 4 km from the center of the crater of Mount Bromo.
            
            Teletubbies hill savannah Mount Bromo
            Is a desert-savannah commonly called by the name of Mount Bromo Teletubbies hill and surrounded by rows of hills. 
            A natural landscape is perfect, it can be said Mount Bromo has a natural charm which is very comprehensive, 
            ranging from beautiful sunrises, splendor Tourism bromo crater, 
            or caldera sea of ​​desert and grass savannah contained in this field. 
            
            Climbing Mount Bromo
            
            Mount Bromo is the best location in Indonesia to see the sun rising very beautiful and charming. 
            In order to achieve Ascent of Mount Bromo, tourists can use the Bromo jeep rental services to deliver to the tourist sites of interest in Mount Bromo. 
            Depart to the summit of Mount Bromo Pananjakan be done in the early morning at around 03.00 am and the trip can be started from the inn where you stay at Mount Bromo, 
            so you do not miss the sunrise in the tourist area of ​​Mount Bromo.</Last-Description>
        <Image>images/bromo.jpg</Image>
    </DetailPulau>
    <DetailPulau ID_PPulau="P002">
        <Nama_pulau>Jawa</Nama_pulau>
        <Name_tempat>MONUMEN NASIONAL(MONAS)</Name_tempat>
        <Small-Description>existing tourist destinations in Indonesia's province of East Java National menyuguhkanMonumen or popularly abbreviated with Monas monument or memorial is as high as 132 meters (433 feet) erected in memory of the resistance and the Indonesian people's struggle for independence from Dutch colonial rule. 
            
            The construction of this monument began on August 17, 1961 under the orders of president Sukarno, and opened to the public on July 12, 1975. This monument crowned with flame-coated gold sheet which symbolizes the spirit of struggle fiery. The National Monument is located right in the center of Merdeka Square, Central Jakarta. 
            Monuments and museums are open every day starting at 08:00 to 15:00 pm. On the last Monday of every month is closed to the public.</Small-Description>
        <Description>History
            After the central government of the Republic of Indonesia returned to Jakarta after previously located in Yogyakarta in 1950 following the recognition of the sovereignty of the Republic of Indonesia by the Dutch government in 1949, President Sukarno began planning the construction of a national monument that is the equivalent of the Eiffel Tower on the ground right in front of the Palace. Monas monument Development aims to commemorate and preserve the Indonesian struggle for independence during the revolution of 1945, in order to continue to inspire patriotism and spirit of the next generation.</Description>
        <Last-Description>At the base of the monument at a depth of 3 meters below ground level, there is the National History Museum Indonesia. Great room museum of history of the national struggle with the size of 80 x 80 meters wide, can accommodate about 500 people visitors. The room is large marble there are 48 dioramas on all four sides and 3 diorama in the middle, so that a total of 51 dioramas. This diorama featuring the history of Indonesia since the pre-history up to the New Order. This diorama dimula from the northeast corner of moving clockwise trace the history of Indonesia; start the pre-history, past ancient empires such as Srivijaya and Majapahit, followed by Europeans during the colonial period that followed the resistance of the pre-independence national hero against the VOC and the Dutch government. Diorama continued until the Indonesian national movement early 20th century, the Japanese occupation, the war of independence and the revolutionary period, until the time of the New Order in the Suharto era.</Last-Description>
        <Image>images/Monas.jpg</Image>
    </DetailPulau>
    <DetailPulau ID_PPulau="P003">
        <Nama_pulau>Jawa</Nama_pulau>
        <Name_tempat>Mount Tangkuban Perahu</Name_tempat>
        <Small-Description>Tangkuban Perahu, or Tangkuban Perahu is one of the mountains which is located in West Java Province, Indonesia. About 20 km to the north of Bandung, with lush pine trees and expanse of tea gardens in the vicinity, Mount Tangkuban Perahu has a height as high as 2,084 meters. Forms of this mountain is Stratovulcano the eruption center that moves from east to west. Rock types are mostly issued by the eruption of lava and sulfur, a mineral which is issued sulfur sulfur, a mineral that was issued when the mountain is not active sulfur vapor. Tangkuban Perahu Mountain area administered by the Corporation of Forestry. Daily average temperature was 17 ° C at noon and 2 ° C at night.
            Mount Tangkuban Perahu has a forest area Dipterokarp Hill, Dipterokarp forest Upper Montane forest, and forest Ericaceous or mountain forests.</Small-Description>
        <Description>MOUNTAIN HISTORICAL BOAT TANGKUBAN BANDUNG
            
            The story of Mount Tangkuban Perahu Bandung is very legendary and full of natural beauty and kontroversial.Di behind the cool and cold of this region, turns attractions in Bandung western save a million mysteries of a case that the writer is a case of incest or incestuous perkawianan the days of yore , which although not yet happened but it is behind the name of a mountain so famous until now.</Description>
        <Last-Description>MOUNTAIN TOUR BOAT TANGKUBAN BANDUNG
